stages:
  - build
  - publish

build:
  stage: build
  tags:
    - docker
  image: centos:8
  variables:
    BUNDLE_VERSION: "1.10.4-7-g0df74ff"

  before_script:
    - echo "Using tarantool-enterprise-bundle ${BUNDLE_VERSION}"
    - curl -O -L https://tarantool:${DOWNLOAD_TOKEN}@download.tarantool.io/enterprise/tarantool-enterprise-bundle-${BUNDLE_VERSION}.tar.gz
    - tar -xzf tarantool-enterprise-bundle-${BUNDLE_VERSION}.tar.gz
    - rm -rf tarantool-enterprise-bundle-${BUNDLE_VERSION}.tar.gz
    - export PATH=$PWD/tarantool-enterprise:$PATH
    - yum -y install java-1.8.0-openjdk
    - yum -y install git gcc make unzip which
    - curl -sSL https://zipkin.apache.org/quickstart.sh | bash -s
    - tarantoolctl rocks install ldoc --server=http://rocks.moonscript.org
    - tarantoolctl rocks install luacheck 0.25.0
    - export PATH=.rocks/bin:$PATH
  script:
    - tarantoolctl rocks make
    - java -jar zipkin.jar &
    - sleep 10
    - make lint
    - make unit
    - ./release.sh
    - make doc
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - doc/
      - release/
      - release-doc/

build-2.x-centos:
  stage: build
  tags:
    - docker
  image: tarantool/tarantool:2.x-centos7

  before_script:
    - yum -y install gcc curl git make unzip which java-1.8.0-openjdk
    - curl -sSL https://zipkin.apache.org/quickstart.sh | bash -s
    - tarantoolctl rocks install ldoc --server=http://rocks.moonscript.org
    - tarantoolctl rocks install luacheck 0.25.0
    - export PATH=.rocks/bin:$PATH
  script:
    - tarantoolctl rocks make
    - java -jar zipkin.jar &
    - sleep 10
    - make lint
    - make unit

publish:
  stage: publish
  dependencies:
    - build
  tags:
    - shell
  when: manual
  only:
    - tags
  script:
    - aws --endpoint-url "${AWS_S3_ENDPOINT_URL}" s3 cp release/*.all.rock "s3://packages/rocks/"
    - aws --endpoint-url "${AWS_S3_ENDPOINT_URL}" s3 cp --recursive release-doc/ "s3://packages/rocks-doc/"
