name: Run tests

on:
  push:
  pull_request:

env:
  ROCK_NAME: "tracing"

jobs:
  run-tests-ce:
    strategy:
      matrix:
        tarantool-version: ["1.10", "2.3", "2.4", "2.5"]
      fail-fast: false
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@master
      - name: Install requirements for community
        run: |
          curl -L https://tarantool.io/installer.sh | sudo VER=${{ matrix.tarantool-version }} bash
          sudo apt install -y tarantool-dev
          curl -sSL https://zipkin.io/quickstart.sh | bash -s
          tarantoolctl rocks install ldoc --server=http://rocks.moonscript.org
          tarantoolctl rocks install luacheck 0.25.0
          export PATH=.rocks/bin:$PATH
          tarantoolctl rocks make
      - name: Run linter
        run: |
          .rocks/bin/luacheck ./tracing --config=.luacheckrc --no-redefined --no-unused-args
          .rocks/bin/luacheck ./test --config=.luacheckrc --no-redefined --no-unused-args
      - name: Run tests
        run: |
          java -jar zipkin.jar &
          sleep 10
          make unit
      - name: Build doc
        run: .rocks/bin/ldoc -t "$ROCK_NAME-${version}" -p "$ROCK_NAME (${version})" --all .

  push-rockspec:
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@master
      - name: Push scm rockspec
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          curl --fail -X PUT -F rockspec=@$ROCK_NAME-scm-1.rockspec \
            https://${{ secrets.ROCKS_USERNAME }}:${{ secrets.ROCKS_PASSWORD }}@${{ secrets.ROCKS_SERVER }}
      - name: Push release rockspec
        if: github.event_name == 'push' && github.ref == 'refs/tags/'
        run: |
          curl --fail -X PUT -F rockspec=@$ROCK_NAME-scm-1.rockspec \
            https://${{ secrets.ROCKS_USERNAME }}:${{ secrets.ROCKS_PASSWORD }}@${{ secrets.ROCKS_SERVER }} \
          cat $ROCK_NAME-scm-1.rockspec |
              sed -E \
                -e "s/branch = '.+'/tag = '$GITHUB_REF'/g" \
                -e "s/version = '.+'/version = '$GITHUB_REF-1'/g" |
              curl --fail -X PUT -F "rockspec=@-;filename=$ROCK_NAME-$GITHUB_REF-1.rockspec" \
                https://${{ secrets.ROCKS_USERNAME }}:${{ secrets.ROCKS_PASSWORD }}@rocks.tarantool.org
